# Generated by Django 3.1.3 on 2020-12-01 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('new_todolist', '0003_auto_20201201_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2020, 12, 1, 17, 57, 23, 808557, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
