# Generated by Django 3.1.3 on 2020-12-01 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_todolist', '0004_auto_20201201_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
