# Generated by Django 3.1.3 on 2020-12-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_todolist', '0005_auto_20201201_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='itemName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
