# Generated by Django 3.1.3 on 2020-12-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_todolist', '0007_auto_20201202_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0)),
                ('todoListName', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
